# Check https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2.1

commands:
  import_gpg_key:
    steps:
      - run:
          name: import GPG key
          command: echo -e "$GPG_KEY_BASE64" | base64 -d | gpg --batch --yes --import
  decrypt_blackbox:
    steps:
      - run:
          name: decrypt all blackbox files
          command: blackbox_postdeploy
  restore_ohmycardsweb_cache:
    steps:
      - restore_cache:
          key: ohmycardsweb
          

jobs:

  test:
    docker: 
      - image: vitorqb23/oh-my-cards-circle-ci-primary:9
    steps:
      - checkout
      - restore_cache:
          key: ohmycardsweb
      - run: make install build/test karma KARMA_OPTS='--single-run'
      - save_cache:
          paths: [~/.m2]
          key: ohmycardsweb

  build:
    docker:
      - image: vitorqb23/oh-my-cards-circle-ci-primary:9
    steps:
      - checkout
      - import_gpg_key
      - decrypt_blackbox
      - restore_ohmycardsweb_cache
      - setup_remote_docker
      - run:
          name: Builds the application
          command: cd devops && make images/prod DOCKER='docker'

  create_docker_image:
    docker:
      - image: vitorqb23/oh-my-cards-circle-ci-primary:9
    steps:
      - checkout
      - import_gpg_key
      - decrypt_blackbox
      - restore_ohmycardsweb_cache
      - setup_remote_docker
      - run:
          name: Builds image
          command: cd devops && make images/prod DOCKER='docker'
      - run:
          name: Pushes image to repository
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push "vitorqb23/ohmycards-web:$(git describe --tags)"    
      - save_cache:
          paths: [~/.m2]
          key: ohmycardsweb

  compile_scss:
    docker:
      - image: vitorqb23/oh-my-cards-circle-ci-primary:9
    steps:
      - checkout
      - run: make install scss/once


workflows:
  version: 2
  test:
    jobs:
      - test: {}
  build:
    jobs:
      - build:
          context: main
          filters:
            branches:
              ignore:
                - master
  create_docker_image:
    jobs:
      - create_docker_image:
          context: main
          filters:
            branches:
              only:
                - master
                - circlecitest
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
  compile_scss:
    jobs:
      - compile_scss:
          filters:
            branches:
              ignore:
                - master

