# Check https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2
jobs:
  test:
    docker: 
      - image: vitorqb23/oh-my-cards-circle-ci-primary
    steps:
      - checkout
      - run: |
          npm install
          make build/test 
          make karma KARMA_OPTS='--single-run'
  create_docker_image:
    docker:
      - image: vitorqb23/oh-my-cards-circle-ci-primary
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          cd devops && make images/prod DOCKER='docker'
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push "vitorqb23/ohmycards-web:$(git describe --tags)"    
          
workflows:
  version: 2
  test_and_create_docker_image:
    jobs:
      - test: {}
      - create_docker_image:
          filters:
            branches:
              only:
                - master
          requires:
            - test
          context: main
