(ns ohmycards.web.kws.common.async-actions.core)

(def ^:const state "The atom-like containing the state." ::state)
(def ^:const run-condition-fn "A 1-arg function that receives the dereferred state and returns a a logical-true value that decides if the action should be run or not. It may return a normal value or a channel. A channel that get's closed is the same as a channel that sends `false`. Notice this is run before any other hook/reducer." ::run-condition-fn)
(def ^:const pre-reducer-fn "A 1-arg fn used to reduce the state before the action." ::pre-reducer-fn)
(def ^:const pre-hook-fn "A 0-arg fn called before the action." ::pre-hook-fn)
(def ^:const post-reducer-fn "A 2-arg fn used to reduce the state after the action. Receives the payload from the action." ::post-reducer-fn)
(def ^:const post-hook-fn "A 1-arg fn called after the action with the result." ::post-hook-fn)
(def ^:const action-fn "A 1-arg fn that runs the action. It receives the dereferred state and must return a channel with the response." ::action-fn)
(def ^:const return-value-fn "A 2-arg fn that receives the payload for the action and the derrefered state. This fn defined the return value of the entire action `run`. The `run` method will always return a channel with the return value of this fn. As a default, simply pass the action raw result." ::return-value-fn)
