(ns test-ns-requires
  "Namespace used to require all tests namespaces.
  THIS FILE IS CREATED AUTOMATICALLY AND SHOULD NOT BE EDITED.
  See make test-ns-requires"
  (:require
[ohmycards.web.common.cards.core-test]
[ohmycards.web.common.coercion.coercers-test]
[ohmycards.web.common.coercion.core-test]
[ohmycards.web.common.coercion.result-test]
[ohmycards.web.common.tags.core-test]
[ohmycards.web.common.utils-test]
[ohmycards.web.components.current-view.core-test]
[ohmycards.web.components.form.core-test]
[ohmycards.web.components.form.input-test]
[ohmycards.web.components.header.core-test]
[ohmycards.web.components.inputs.tags-test]
[ohmycards.web.components.loading-wrapper.core-test]
[ohmycards.web.core-test]
[ohmycards.web.services.cards-crud.core-test]
[ohmycards.web.services.events-bus.core-test]
[ohmycards.web.services.fetch-cards.core-test]
[ohmycards.web.services.http-test]
[ohmycards.web.services.http.utils-test]
[ohmycards.web.services.login.core-test]
[ohmycards.web.services.login.get-token-test]
[ohmycards.web.services.login.onetime-password-test]
[ohmycards.web.services.login.utils-test]
[ohmycards.web.utils.components-test]
[ohmycards.web.utils.pagination-test]
[ohmycards.web.views.cards-grid.config-dashboard.core-test]
[ohmycards.web.views.cards-grid.config-dashboard.state-management-test]
[ohmycards.web.views.cards-grid.control-header-test]
[ohmycards.web.views.cards-grid.core-test]
[ohmycards.web.views.cards-grid.state-management-test]
[ohmycards.web.views.edit-card.core-test]
[ohmycards.web.views.edit-card.handlers-test]
[ohmycards.web.views.edit-card.state-management-test]
[ohmycards.web.views.login.core-test]
[ohmycards.web.views.login.email-row-test]
[ohmycards.web.views.login.handlers.submit-test]
[ohmycards.web.views.new-card.core-test]
[ohmycards.web.views.new-card.form-test]
[ohmycards.web.views.new-card.handlers.create-card-test]
[ohmycards.web.views.new-card.header-test]
))
